using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Server.Model;

namespace Server.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class KdramaController : ControllerBase
    {
        [HttpGet]
        public IActionResult GetAllKdrama()
        {
            List<Kdrama> kdramas = new List<Kdrama>()
            {
                new Kdrama{Id = 1, Name = "King The Land", Episode = 16, PicUrl = "https://s1.lk21static.xyz/wp-content/uploads/2023/06/film-king-the-land-2023-lk21-d21.jpg.webp", Genre = "Comedy, Romance", Cast = "Lee Junho, Im Yoon-ah", Synopsis = "Anggun, karismatik, cerdas, dan chic, pewaris King Group Goo Won memiliki segalanya kecuali kenangan tentang ibunya. Dalam upaya untuk memulihkan ingatannya, ia kembali ke King Hotel. Dikenal sebagai ratu senyum dan keramahtamahan King Hotel, Cheon Sa-rang bekerja dari meja depan hingga sekarang bekerja di ruang \"King the Land\" yang glamor, di mana dia bertemu Goo Won."},
                new Kdrama{Id = 2, Name = "Twenty Five Twenty One", Episode = 16, PicUrl = "https://s7.lk21static.xyz/wp-content/uploads/2022/02/film-twenty-five-twenty-one-2022-lk21-d21.jpg.webp", Genre = "Drama, Romance", Cast = "Nam Jo Hyuk, Kim Tae Ri, Choi Hyun Wook", Synopsis = "Pada saat mimpi tampak di luar jangkauan, seorang atlet anggar remaja mengejar ambisi besar dan bertemu dengan seorang pemuda pekerja keras yang berusaha membangun kembali hidupnya."},
                new Kdrama{Id = 3, Name = "Bloodhounds", Episode = 8, PicUrl = "https://s6.lk21static.xyz/wp-content/uploads/2023/06/film-bloodhounds-2023-lk21-d21.jpg.webp", Genre = "Action, Crime, Drama", Cast = "Park Sung-woong, Si Won Choi, Woo Do-Hwan", Synopsis = "Untuk melunasi hutang mereka, tiga pemuda pemberani terjun ke bisnis peminjaman uang sambil menghadapi orang kaya dan berkuasa yang memangsa yang lemah." },
                new Kdrama{Id = 4, Name = "The K2", Episode = 16, PicUrl = "https://s1.lk21static.xyz/wp-content/uploads/2022/04/film-the-k2-2016-lk21-d21.jpg.webp", Genre = "Drama, Romance, Thriller", Cast = "Im Yoon-ah, Ji Chang-Wook, Song Yun-ah", Synopsis = "Kim Je Ha adalah mantan tentara yang disewa. Dia juga disebut K2. Ia dipekerjakan sebagai pengawal oleh Choi Yoo Jin. Choi Yoo Jin adalah istri Jang Se Joon, yang mencalonkan diri sebagai presiden. Sementara itu, Go Anna adalah putri tidak sah yang tertutup dari Jang Se Joon yang harus dijaga Je Ha." },
                new Kdrama{Id = 5, Name = "Blind", Episode = 16, PicUrl = "https://s2.lk21static.xyz/wp-content/uploads/2022/09/film-blind-2022-lk21-d21.jpg.webp", Genre = "Drama, Mystery, Thriller", Cast = "Eun-ji Jung, Ha Seok-jin, Ok Taecyeon", Synopsis = "Menceritakan Sebuah cerita tentang orang-orang yang telah menjadi korban ketidakadilan karena mereka adalah pelaku biasa dan biasa yang telah memperhatikan kebenaran yang tidak nyaman." },
                new Kdrama{Id = 6, Name = "The First Responders", Episode = 12, PicUrl = "https://s1.lk21static.xyz/wp-content/uploads/2022/11/film-the-first-responders-2022-lk21-d21.jpg.webp", Genre = "Action, Drama, Thriller", Cast = "Kim Rae-won, Son Ho-jun", Synopsis = "Catatan lapangan respons bersama antara polisi yang menangkap penjahat dan petugas pemadam kebakaran yang menangkap api. Kantor polisi dan kantor pemadam kebakaran bersama-sama menanggapi adegan sengit antara kejahatan, bencana, dan keadaan darurat." },
                new Kdrama{Id = 7, Name = "Taxi Driver", Episode = 16, PicUrl = "https://s6.lk21static.xyz/wp-content/uploads/2021/11/film-taxi-driver-mobeomtaeksi-2021-d21.jpg.webp", Genre = "Action, Crime, Drama", Cast = "Esom, Eui-sung Kim, Lee Jehoon", Synopsis = "Kisah seorang sopir taksi mewah yang membalas dendam atas nama penumpangnya." },
                new Kdrama{Id = 8, Name = "D.P", Episode = 6, PicUrl = "https://s6.lk21static.xyz/wp-content/uploads/2022/01/film-d-p-2021-lk21-d21.jpg.webp", Genre = "Action, Crime, Drama", Cast = "Harrison Xu, Jung Hae-In, Sukku Son", Synopsis = "An Joon-Ho (Jung Hae-In) adalah seorang prajurit. Dia pendiam dan tenang, tapi tidak fleksibel. Sersan Park Beom-Goo (Kim Sung-Kyun) memperhatikan keuletan dan kemampuan Pribadi An Joon-Ho untuk mengamati. Dia mentransfer An Joon-Ho ke tim D.P. (Deserter Pursuit). Misi mereka adalah untuk menangkap desertir. An Joon-Ho bekerja dengan Sersan Park Beom-Goo dan Kopral Han Ho-Yeol (Koo Gyo-Hwan) di tim. Sersan Park Beom-Goo terlihat lelah sepanjang waktu. Dia mengutuk dan mengomel pada An Joon-Ho dan Han Ho-Yeol, tetapi dia juga merawat mereka dengan wawasannya yang tajam. Han Ho-Yeol kadang-kadang memberi Tahu an Joon-Ho, tetapi dia kadang-kadang mengganggunya. Sementara itu, Letnan Satu Im Ji-Seob (Son Seok-Koo) hanya peduli dengan kesuksesannya di militer. Dia tidak peduli dengan tim D.P." },
                new Kdrama{Id = 9, Name = "Connect", Episode = 6, PicUrl = "https://s0.lk21static.xyz/wp-content/uploads/2022/12/film-connect-2022-lk21-d21.jpg.webp", Genre = "Crime, Drama, Fantasy", Cast = "Go Kyung-Pyo, Jung Hae-In, Kim Hye-jun", Synopsis = "Menceritakan Seorang pria diculik dan salah satu matanya dilepas oleh sekelompok pemburu organ. Matanya ditransplantasikan ke tubuh seorang pembunuh berantai. Donor yang tidak mau sekarang memiliki penglihatan yang mengerikan saat dia menyaksikan serangan mengerikan terhadap penduduk Seoul." },
                new Kdrama{Id = 10, Name = "Weak Hero Class 1", Episode = 8, PicUrl = "https://s1.lk21static.xyz/wp-content/uploads/2022/11/film-weak-hero-class-1-yakhanyeongung-2022-lk21-d21.jpg.webp", Genre = "Action", Cast = "Choi Hyun-Wook, Ji-Hoon Park, Kyung Hong", Synopsis = "Yeon Shi Eun adalah siswa teladan, yang menempati peringkat teratas di sekolahnya. Secara fisik, ia tampak seperti anak yang lemah, tetapi, dengan menggunakan kecerdasan, alat, dan psikologinya, ia berjuang melawan kekerasan yang terjadi di dalam dan di luar sekolahnya." },
                new Kdrama{Id = 11, Name = "Healer", Episode = 20, PicUrl = "https://s7.lk21static.xyz/wp-content/uploads/2022/06/film-healer-hilleo-2014-lk21-d21.jpg.webp", Genre = "Action, Comedy, Crime", Cast = "Ji Chang-Wook, Park Min-Young, Tae-Mi", Synopsis = "Insiden pembunuhan lama yang melibatkan kelompok yang menjalankan stasiun penyiaran ilegal menyatukan orang-orang yang berbeda - seorang pesuruh misterius \"Penyembuh\" yang memiliki keterampilan penyamaran dan pertempuran, seorang reporter dari tabloid kelas dua, dan seorang jurnalis terkenal. Mereka harus berurusan dengan konflik kebenaran versus iman yang kejam." },
                new Kdrama{Id = 12, Name = "Melting Me Softly", Episode = 16, PicUrl = "https://s1.lk21static.xyz/wp-content/uploads/2022/01/film-melting-me-softly-nal-nokyeojuo-2019-lk21-d21.jpg.webp", Genre = "Comedy, Drama, Fantasy", Cast = "Ji Chang-Wook, Jin-ah Won, Yun Se-ah", Synopsis = "Ini adalah komedi romantis sci-fi. Kisah ini bercerita tentang seorang pria dan seorang wanita yang berpartisipasi dalam percobaan pembekuan manusia 24 jam. Karena skema misterius, pasangan itu bangun 20 tahun kemudian." },
                new Kdrama{Id = 13, Name = "Island", Episode = 12, PicUrl = "https://s1.lk21static.xyz/wp-content/uploads/2022/12/film-island-2022-lk21-d21.jpg.webp", Genre = "Action, Adventure, Fantasy", Cast = "Cha Eun-Woo, Lee Da-hee, Nam-gil Kim", Synopsis = "Sikap Won Mi Ho yang arogan dan egois menyebabkan ayahnya membuangnya ke pulau Jeju. Tanpa sepengetahuannya, pulau itu adalah tempat kejahatan berkeliaran bebas." },
                new Kdrama{Id = 14, Name = "The Good Bad Mother", Episode = 14, PicUrl = "https://s6.lk21static.xyz/wp-content/uploads/2023/04/film-the-good-bad-mother-2023-lk21-d21.jpg.webp", Genre = "Comedy, Crime, Drama", Cast = "Eun-Jin Ahn, Lee Do-Hyun, Ra Mi-ran", Synopsis = "Sebuah drama tentang seorang ibu, Young Soon, yang telah hidup untuk anaknya sepanjang hidupnya, dan putranya, jaksa Kang Ho, yang menderita amnesia dalam kecelakaan tak terduga dan kembali menjadi seorang anak." },
                new Kdrama{Id = 15, Name = "Revenge Of Other", Episode = 12, PicUrl = "https://s0.lk21static.xyz/wp-content/uploads/2022/11/film-revenge-of-others-2022-lk21-d21.jpg.webp", Genre = "Drama, Mystery, Thriller", Cast = "Park Solomon, Kim Joo-Ryung, Seo Ji-Hoon, Ye-Eun Shin", Synopsis = "Mengikuti kisah Ok Chan-mi saat dia berusaha membalas dendam atas kematian saudara kembarnya." },
                new Kdrama{Id = 16, Name = "All Of Us Are Dead", Episode = 12, PicUrl = "https://s1.lk21static.xyz/wp-content/uploads/2022/01/film-all-of-us-are-dead-jigeum-uri-hakgyoneun-2022-lk21-d21.jpg.webp", Genre = "Action, Drama, Fantasy", Cast = "Park Ji-hoo, Yoon Chang-young, Park Solomon", Synopsis = "Sekilas yang mencolok dari pertempuran sengit antara siswa yang berubah menjadi zombie dan orang-orang yang selamat putus asa untuk melarikan diri. Ini dibuka dengan seorang siswa di laboratorium sekolah, mengundang penonton untuk mencari tahu lebih banyak tentang virus yang menciptakan kekacauan total. Visual mengerikan siswa yang terinfeksi oleh virus zombie misterius dan aksi menakjubkan yang ditetapkan di berbagai bagian sekolah juga harus diperhatikan. Terperangkap di sekolah yang penuh virus tanpa ponsel, tidak ada makanan, dan tidak ada yang merawat mereka, para siswa meraih lampu meja, rak buku, dan busur untuk membela diri dari zombie Dalam perjuangan putus asa untuk bertahan hidup." },
            };
            return Ok(kdramas);
        }
    }
}
